### ISSUE TITLE
 Error inflating

### ISSUE THREAD

**Issue by GauravCreed** [Nightonke/JellyToggleButton#2]
Hi @Nightonke 

JellyToggleButton is great library, i have little issue on that.

I just put **compile 'com.nightonke:jellytogglebutton:1.0.2'** in my project gradle file it will work fine,but whenever i am using **android.support.design.widget.NavigationView** with JellyToggleButton in my activity it will generate error like...

`Process: com.richard.wallpaperapps, PID: 15068
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.richard.wallpaperapps/com.gordonwong.materialsheetfab.sample.MainActivity}: android.view.InflateException: Binary XML file line #48: Error inflating class android.support.design.widget.NavigationView
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2493)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2555)
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:176)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                               at android.os.Looper.loop(Looper.java:194)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5576)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
                                                                            Caused by: android.view.InflateException: Binary XML file line #48: Error inflating class android.support.design.widget.NavigationView
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276)
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136)
                                                                               at com.gordonwong.materialsheetfab.sample.MainActivity.onCreate(MainActivity.java:60)
                                                                               at android.app.Activity.performCreate(Activity.java:6005)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2446)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2555) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:176) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                               at android.os.Looper.loop(Looper.java:194) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5576) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751) 
                                                                            Caused by: java.lang.reflect.InvocationTargetException
                                                                               at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:607)
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136) 
                                                                               at com.gordonwong.materialsheetfab.sample.MainActivity.onCreate(MainActivity.java:60) 
                                                                               at android.app.Activity.performCreate(Activity.java:6005) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2446) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2555) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:176) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                               at android.os.Looper.loop(Looper.java:194) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5576) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751) 
                                                                            Caused by: java.lang.NoClassDefFoundError: android.support.design.internal.NavigationMenuPresenter
                                                                               at android.support.design.widget.NavigationView.<init>(NavigationView.java:80)
                                                                               at android.support.design.widget.NavigationView.<init>(NavigationView.java:92)
                                                                               at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
                                                                               at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
                                                                               at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:276) 
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:136) 
                                                                               at com.gordonwong.materialsheetfab.sample.MainActivity.onCreate(MainActivity.java:60) 
                                                                               at android.app.Activity.performCreate(Activity.java:6005) 
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111) 
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2446) 
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2555) 
                                                                               at android.app.ActivityThread.access$800(ActivityThread.java:176) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                               at android.os.Looper.loop(Looper.java:194) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5576) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) `

i don't know why this is happening here is my gradle File ....

`dependencies {
    compile project(':material-sheet-fab')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:design:23.0.1'
    compile 'com.android.support:cardview-v7:23.0.1'
    compile 'com.android.support:recyclerview-v7:23.0.1'
    compile 'com.google.android.gms:play-services-ads:8.4.0'
    compile 'org.apache.httpcomponents:httpmime:4.5.2'
    compile 'org.jbundle.util.osgi.wrapped:org.jbundle.util.osgi.wrapped.org.apache.http.client:4.1.2'
    compile 'com.edmodo:cropper:1.0.1'
    compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'io.github.hendraanggrian:dangerous:0.1.1'
    compile 'com.google.android.gms:play-services:8.4.0'
    compile 'com.android.volley:volley:1.0.0'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.github.siyamed:android-shape-imageview:0.9.+@aar'
    compile 'com.github.ivbaranov:materialfavoritebutton:0.1.2'
    compile 'me.gujun.android.taggroup:library:1.4@aar'
    compile 'com.nightonke:jellytogglebutton:1.0.2'

```
compile('com.crashlytics.sdk.android:crashlytics:2.6.0@aar') {
    transitive = true;
}
compile files('libs/AudienceNetwork.jar')
```

}`

please give me any solution for that..

Thanks.

**Comment by Nightonke** [comment]
Emmm... Have you tried to use just NavigationView without Jelly?

**Comment by GauravCreed** [comment]
yes i have already implemented, i have a both code in separate and now i just combine that

**Comment by aesion** [comment]
额....
